### PR TITLE
CM-1485 Do not call setSecret

### PR DESCRIPTION
**Pull request by alexander2001i**

### CODE REVIEW

**Comment by alexander2001i** [comment]
@watchtower314 Any progress on that?

**Comment by watchtower314** [comment]
> @watchtower314 Any progress on that?

Not yet, I was working on the moderation batch 2, I'm hoping to work on this later today :)

**Comment by alexander2001i** [comment]
@watchtower314 Should we just close this?

**Comment by watchtower314** [comment]
> @watchtower314 Should we just close this?

@alexander2001i  I missed this 🤦🏻‍♀️ for some reason I stopped getting notification about comments on pr 🤷🏽‍♀️

I will work on it now, unless you think we should close this?

**Comment by alexander2001i** [comment]
@watchtower314 yes, don't waste your time

**Pull request closed without merging**
