### PR TITLE
Cm 888 More reporting work

### PR DESCRIPTION
**Pull request by Amosel**
These scripts create 4 different pay-in css reports.
1. All pay ins made in the system.
2. All pay ins per each user
3. All pay ins per common user
4. All commons report.

These scripts are battle tested and circumvent records on the db and the major data inconsistencies:
1. Many Payment records do not include a common Id, thus the scripts lookup the proposal id in the payment record (which is the join request for that paying user), then gets the common by looking up the commonId of that proposal. 
2. Some common raised numbers do not align with the actual number of pay ins to that common, that is reflected in the commons report.

Additional there are tested scripts to duplicate the whole database that are used to create integration with big query.

Comments:
The most recent change to the record types were overcome
- missing `PaymentType` was created locally.
- `PaymentType` is ignoring the fact that `paid` key is [present in the database](https://console.firebase.google.com/u/0/project/common-daostack/firestore/data/~2Fpayments~2F7069dc31-ff15-4b3a-8d0e-d2ff08a58ab2 ) PaymentType ` was created locally.
- IPayment `fees` changed to `fee` although all 1467 old payments records have that field. A new version of `Payment` was created locally.

### CODE REVIEW

**Comment by ariel-dao** [comment]
IPayment fees - `fee` is a typo, will be changed back to `fees`

**Comment by ariel-dao** [comment]
@Amosel updated dev branch please recheck your code, fee was changed back to fees

**Review by SobolevYuri — DISMISSED** [review]

**Comment by Amosel** [comment]
@SobolevYuri let me know if you have any questions.

**Comment by ariel-dao** [comment]
PR is obsolete, all financial related exporting is done in https://github.com/daostack/common-backoffice. Closing.

**Pull request closed without merging**
