### PR TITLE
Add DM list endpoint

### LINKED ISSUE #1731: Direct message user list endpoint
All users from all commons\projects which the current user is member of

### PR DESCRIPTION
**Pull request by danielr18**
Closes #1731

### CODE REVIEW

**Comment by danielr18** [comment]
@ariel-dao 

1 - Under which firebase function are we going to have the DM functionality? I currently have it in `/users` while it's in review, but I would prefer to have it in the same one as https://github.com/daostack/common-backend/issues/1732

2 - The endpoint is slow because it has to get all commons, figure out if you are a member, and then get all the other members and their user objects... How should we improve the speed? I know we are no longer using Redis, so, should we create new auxiliary collections, for example one where you can have an array of all the commons you are a member of?

**Comment by danielr18** [comment]
For 1. I've moved it to `/direct`.

**Comment by ariel-dao** [comment]
@danielr18 I'll get back to it after DMs are implemented

**Comment by ariel-dao** [comment]
@danielr18 It's going to be under `/chat/`
see: https://github.com/daostack/common-backend/pull/1766

If the slowness is serious, feel free to create a new collection to support this endpoint

**Pull request merged**
