### PR TITLE
added a discussion message counter

### PR DESCRIPTION
**Pull request by noamso1**

### CODE REVIEW

**Comment by noamso1** [comment]
DONT MERGE YET PLEASE. still need to test, and move migration first time script to somewhere else.

**Comment by noamso1** [comment]
Tested it. it works. now we need to decide where to put the migration script that populates all the current messageCount fields in all discussions. any idea where to put it ?

**Comment by ariel-dao** [comment]
@noamso1 we'll need to run it manually when it goes up in each production

**Comment by noamso1** [comment]
So now the current method to fire the migration is to post a message with this exact text: "countAllDiscussionMessages".

**Review by ariel-dao — APPROVED** [review]

**Pull request merged**
